name: "Deploy Examples Explorer v4 (https://examples4.ext.net/)"

on:
  push:
    branches: [ 4 ]
jobs:
  publish:
    name: "Deploy examples explorer v4"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 0

    - name: Deploy files changed
      uses: objectdotnet/action-ftp-deploy-then-slack-notification@0.2.0
      with:
        repo-root: src
        ftp-host: ${{ secrets.iis_ftp_host }}
        ftp-user: ${{ secrets.iis_ftp_user }}
        ftp-pass: ${{ secrets.iis_ftp_pass }}
        ftp-root: examples4.ext.net/wwwroot
        slack-webhook:  ${{ secrets.SLACK_WEBHOOK }}
        slack-nick: "Examples Explorer v4 Deploy Service"
        slack-icon: ":extglow:"
